table circuits
	lineageTag: 19f8b178-bf23-4314-9c83-8684bbe6a831

	column circuitId
		dataType: int64
		formatString: 0
		lineageTag: 580be271-1404-4e82-801d-d4db807552b1
		summarizeBy: none
		sourceColumn: circuitId

		annotation SummarizationSetBy = Automatic

	column circuitRef
		dataType: string
		lineageTag: 6b1def00-5052-4a30-8faa-bc2e5d53cf52
		summarizeBy: none
		sourceColumn: circuitRef

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 3a7fa3bb-65c8-4fcd-92a9-b8a8ea0244cd
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: b92b0623-81aa-40e8-a813-8e802fd18bc0
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: b70e2d8c-37f2-4860-9545-ba27cb3a6a11
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: double
		lineageTag: 673b0d4d-a3fc-4b4a-9029-4ca83e987b18
		summarizeBy: none
		sourceColumn: lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lng
		dataType: double
		lineageTag: 0d831096-43c3-4856-a0dc-3fd58923592d
		summarizeBy: none
		sourceColumn: lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alt
		dataType: int64
		formatString: 0
		lineageTag: 4404dee4-5d5a-49f0-a968-d4cec0887059
		summarizeBy: none
		sourceColumn: alt

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: b2d9edc6-0e1b-4a2d-9812-34ff1e4bd0c5
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition circuits = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/circuits.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"circuitId", Int64.Type}, {"circuitRef", type text}, {"name", type text}, {"location", type text}, {"country", type text}, {"lat", type number}, {"lng", type number}, {"alt", Int64.Type}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

