table circuits
	lineageTag: 332a1383-026d-477a-8a8e-29ed796f02dd

	column circuitId
		dataType: int64
		formatString: 0
		lineageTag: 0cde9cf2-ffa1-4445-a51f-8d5c77100eb2
		summarizeBy: none
		sourceColumn: circuitId

		annotation SummarizationSetBy = Automatic

	column circuitRef
		dataType: string
		lineageTag: aca91e46-bff1-449b-90e2-0b61b048f974
		summarizeBy: none
		sourceColumn: circuitRef

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 507a60ba-9f92-4e45-8249-25efe479e877
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: bb6a3aa7-7463-4ca2-be88-a2df3a51ba38
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 4aa3cc4d-1f14-44f6-bb1c-b0355e8482f5
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: double
		lineageTag: 16cd0fb1-c6eb-46e5-a920-0e4d7cc908e1
		summarizeBy: none
		sourceColumn: lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lng
		dataType: double
		lineageTag: 3c39f8fd-7471-497f-b89d-fa05a6874e6e
		summarizeBy: none
		sourceColumn: lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alt
		dataType: int64
		formatString: 0
		lineageTag: 531b3271-9512-4fe0-8c2f-5f4b336c91cc
		summarizeBy: none
		sourceColumn: alt

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: a1864050-3ee4-4adb-b616-f830143977ce
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition circuits = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\circuits.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"circuitId", Int64.Type}, {"circuitRef", type text}, {"name", type text}, {"location", type text}, {"country", type text}, {"lat", type number}, {"lng", type number}, {"alt", Int64.Type}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

