table circuits
	lineageTag: 5fe84809-f719-4a64-87d0-381599632eb8

	column circuitId
		dataType: int64
		formatString: 0
		lineageTag: a3e4d2d9-331e-457b-ab38-076cefe3a65d
		summarizeBy: none
		sourceColumn: circuitId

		annotation SummarizationSetBy = Automatic

	column circuitRef
		dataType: string
		lineageTag: cbcaaac5-2430-4fa4-839e-7f3924613b2c
		summarizeBy: none
		sourceColumn: circuitRef

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 12662701-f648-4f06-af81-8e391a5f0267
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: f19e5068-a5d4-497b-9c5b-59fed0eb88ae
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: f1e4da07-1330-488d-bacc-8fe31523a417
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: double
		lineageTag: 820112cc-ea0d-4362-9b03-c0cd2b5c0ef6
		summarizeBy: none
		sourceColumn: lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lng
		dataType: double
		lineageTag: b9f34c84-1b68-4881-a680-b6ff8efc5d24
		summarizeBy: none
		sourceColumn: lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alt
		dataType: int64
		formatString: 0
		lineageTag: 641d90e5-fab6-459e-a07e-e3a7a0a7328f
		summarizeBy: none
		sourceColumn: alt

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: d3f41e86-c424-4c02-a9fd-9f492a22e64d
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition circuits = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MySQL\f1\circuits.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"circuitId", Int64.Type}, {"circuitRef", type text}, {"name", type text}, {"location", type text}, {"country", type text}, {"lat", type number}, {"lng", type number}, {"alt", Int64.Type}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

