table constructors
	lineageTag: d9a519bd-7460-46ae-b440-8f798915f9d1

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 03d667f1-704a-40f7-b51a-2c52579813ce
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column constructorRef
		dataType: string
		lineageTag: f636a480-5dac-4cdf-890d-40a4bdcabbf7
		summarizeBy: none
		sourceColumn: constructorRef

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 306dec15-30b4-4838-933c-63f1560fc885
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column nationality
		dataType: string
		lineageTag: 1cde6307-3dda-4f7b-a2a3-c7f31dedebc5
		summarizeBy: none
		sourceColumn: nationality

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: d87a5a77-aa4b-48db-b60d-71dcfc3239dc
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition constructors = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MySQL\f1\constructors.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorId", Int64.Type}, {"constructorRef", type text}, {"name", type text}, {"nationality", type text}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

