table constructor_standings
	lineageTag: d801ef17-f4cb-4fdc-bf7e-9e230148343c

	column constructorStandingsId
		dataType: int64
		formatString: 0
		lineageTag: df7a98e7-b1a5-4c2d-97eb-64ea06b023d5
		summarizeBy: count
		sourceColumn: constructorStandingsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: b7001c0a-9cf1-4c84-b728-2ba0c8ea37ce
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 510dcdf9-9214-465d-b69a-b7c57358b002
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 097c3569-7b62-4265-b932-e8bbce1dccfc
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: 57c7ddc0-c7bb-460b-a23c-30453a110c65
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: string
		lineageTag: e6489d83-9f76-42b9-81dc-b6fdb13b84f5
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: 754d8445-be3a-4dab-8607-2b049a3b7f6b
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	partition constructor_standings = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MySQL\f1\constructor_standings.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorStandingsId", Int64.Type}, {"raceId", Int64.Type}, {"constructorId", Int64.Type}, {"points", Int64.Type}, {"position", Int64.Type}, {"positionText", type text}, {"wins", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

