table constructor_results
	lineageTag: 67fe52ca-19cb-438f-843e-6a773515bce7

	column constructorResultsId
		dataType: int64
		formatString: 0
		lineageTag: 3732a705-a7c4-4476-858f-729420d3555c
		summarizeBy: count
		sourceColumn: constructorResultsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: d47ef460-cf3b-4ac9-8a60-6d4d2d90f2ec
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: b7889b8e-842d-403d-b5a9-e54eb5a0c0dd
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: a255668d-fe75-421a-a50b-569396545dc8
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 375117cb-4cbc-43d9-9bed-c2dc5334a893
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition constructor_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MySQL\f1\constructor_results.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorResultsId", Int64.Type}, {"raceId", Int64.Type}, {"constructorId", Int64.Type}, {"points", Int64.Type}, {"status", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

