table constructor_results
	lineageTag: a07897a9-30b9-4841-a91e-b1336d0c457f

	column constructorResultsId
		dataType: int64
		formatString: 0
		lineageTag: b7a470ea-e9f8-45cc-b695-513143aebf11
		summarizeBy: count
		sourceColumn: constructorResultsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: f045563b-3ffc-463d-a19e-c4bfcc082350
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 8d0997b3-f63d-4cf5-8e08-c734144273c8
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 651675c8-bad0-407b-bf6b-148156943dc5
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 0c5f0ce7-72b5-45a0-aceb-e46a87c7e161
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition constructor_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\constructor_results.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorResultsId", Int64.Type}, {"raceId", Int64.Type}, {"constructorId", Int64.Type}, {"points", Int64.Type}, {"status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

