table constructors
	lineageTag: ab1b74ce-13d1-4031-b52b-cd05aebd339e

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 165a958e-f999-42cd-8971-f4250ae732da
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column constructorRef
		dataType: string
		lineageTag: b7179baa-cb14-43c4-af17-cfa48425ac4d
		summarizeBy: none
		sourceColumn: constructorRef

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 4801f381-2e17-4b44-b092-1643a032d248
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column nationality
		dataType: string
		lineageTag: 23716995-245a-495a-bbd9-2535d46e8761
		summarizeBy: none
		sourceColumn: nationality

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 6f2a2253-791d-416a-b24d-555b17288962
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition constructors = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/constructors.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorId", Int64.Type}, {"constructorRef", type text}, {"name", type text}, {"nationality", type text}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

