table constructor_results
	lineageTag: 23d0199c-e726-437e-8593-777521ddf369

	column constructorResultsId
		dataType: int64
		formatString: 0
		lineageTag: 82332bea-6c76-406a-b355-0b1ba2c3c886
		summarizeBy: count
		sourceColumn: constructorResultsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 74a1d2bf-73d0-457c-842b-dec1cfbb412b
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: f3edb3ae-b17a-4061-ba6a-3b90906172e1
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: f8b7848f-77c6-4436-821b-172d5ebe364c
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 0f6e083f-5718-4c3b-a428-a5c1a4b2ec46
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition constructor_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/constructor_results.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorResultsId", Int64.Type}, {"raceId", Int64.Type}, {"constructorId", Int64.Type}, {"points", Int64.Type}, {"status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

