table constructors
	lineageTag: 3cdb2cb3-5dab-4afe-884e-084c27747746

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 5b21d55f-cf55-4c9f-9f28-35d37b00358b
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column constructorRef
		dataType: string
		lineageTag: d545f9b8-5a2d-489a-9984-943cbe0ec1d6
		summarizeBy: none
		sourceColumn: constructorRef

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: a2122c99-78c7-4dfd-bd18-c42d78b4a028
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column nationality
		dataType: string
		lineageTag: ff65d386-6646-4f8b-b249-e9e3a6b737e6
		summarizeBy: none
		sourceColumn: nationality

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 17f51dc1-b1b7-425b-b7f6-5714af21cefd
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition constructors = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\constructors.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorId", Int64.Type}, {"constructorRef", type text}, {"name", type text}, {"nationality", type text}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

