table drivers
	lineageTag: 5a96167f-6adb-44c9-b798-95df08672889

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 8f86da51-95b3-4ebb-81ac-4d8fe507bdfa
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column driverRef
		dataType: string
		lineageTag: 0b9473f6-4cde-4904-ac10-20f7a5536d78
		summarizeBy: none
		sourceColumn: driverRef

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: adbbbf42-ae93-4ff8-824b-b52cf75fc73e
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 329b5b8d-8b6c-456c-911c-3aec810fbfe4
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column forename
		dataType: string
		lineageTag: f029273e-3bc8-4fdc-9ac7-012e2075646c
		summarizeBy: none
		sourceColumn: forename

		annotation SummarizationSetBy = Automatic

	column surname
		dataType: string
		lineageTag: 9642203a-628a-413c-9178-ebd05900ef25
		summarizeBy: none
		sourceColumn: surname

		annotation SummarizationSetBy = Automatic

	column dob
		dataType: dateTime
		formatString: Long Date
		lineageTag: 02cb22a9-a7bd-4652-aa62-ae61883731ea
		summarizeBy: none
		sourceColumn: dob

		variation Variation
			isDefault
			relationship: 50073948-b427-467c-9fbf-26116f003904
			defaultHierarchy: LocalDateTable_9d684f46-6408-4f97-8732-2b4a1d9314f7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nationality
		dataType: string
		lineageTag: f108afe5-a842-4a35-8dee-5d646eb5d799
		summarizeBy: none
		sourceColumn: nationality

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 19663bb6-9489-4b1f-986a-cb4591de9f7a
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column 'Full Name' = 'drivers'[forename] & " " & 'drivers'[surname]
		lineageTag: e3851246-0320-4214-955e-6b84cfe5292d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition drivers = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/drivers.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"driverId", Int64.Type}, {"driverRef", type text}, {"number", type text}, {"code", type text}, {"forename", type text}, {"surname", type text}, {"dob", type date}, {"nationality", type text}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

