table drivers
	lineageTag: 2e23f43e-b021-4646-b80a-fc18437b8291

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 7722b08f-997f-4220-b557-bf36719603cb
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column driverRef
		dataType: string
		lineageTag: f2c15d66-2fc4-4bd7-bd92-96e31d034b0c
		summarizeBy: none
		sourceColumn: driverRef

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 59ce95e7-37df-4d84-b7ef-2f348957ce36
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 645a7f3c-0166-4521-a961-3ce19a12ecfc
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column forename
		dataType: string
		lineageTag: 2a8f7cac-e38b-49c6-83f2-4519b7b4a9a5
		summarizeBy: none
		sourceColumn: forename

		annotation SummarizationSetBy = Automatic

	column surname
		dataType: string
		lineageTag: 36342d03-fa44-4d66-9664-80ec1edc6c3c
		summarizeBy: none
		sourceColumn: surname

		annotation SummarizationSetBy = Automatic

	column dob
		dataType: dateTime
		formatString: Long Date
		lineageTag: a6d05d30-81b9-4086-9d90-c71ae1d18a91
		summarizeBy: none
		sourceColumn: dob

		variation Variation
			isDefault
			relationship: 8c03bc69-a31d-4ade-8402-a2899d6a29e8
			defaultHierarchy: LocalDateTable_ea81a2aa-bfe9-4c47-ace3-b263dab1f443.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nationality
		dataType: string
		lineageTag: 2360e8a2-318a-4685-8980-a8f4e2060d4e
		summarizeBy: none
		sourceColumn: nationality

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: df2a85e4-0ad6-4e00-a02f-968ae861d51a
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column 'Full Name' = 'drivers'[forename] & " " & drivers[surname]
		lineageTag: d15ca48a-468c-4b9e-819b-c123eca68dba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition drivers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\drivers.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"driverId", Int64.Type}, {"driverRef", type text}, {"number", type text}, {"code", type text}, {"forename", type text}, {"surname", type text}, {"dob", type date}, {"nationality", type text}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

