table driver_standings
	lineageTag: d925ba47-86d4-4443-813f-0fe12f46c585

	column driverStandingsId
		dataType: int64
		formatString: 0
		lineageTag: 11dbe87c-e4ca-48bd-88de-d703f2bea8e6
		summarizeBy: count
		sourceColumn: driverStandingsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 35ef7914-efb5-45f9-b8ef-03dbdf1dd156
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 23eab956-a7ff-497c-8889-221140d382f9
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 28e7380f-cd53-4069-866e-36fdf0912d44
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: ee8fda23-aaa8-41aa-aa8f-a3ff8ebfc9f0
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: int64
		formatString: 0
		lineageTag: f56453a3-e735-43c5-aa4b-eb0199e429fb
		summarizeBy: sum
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: 8b56116c-7ddb-4ab8-aae2-84e4d6e654a4
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	partition driver_standings = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\driver_standings.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"driverStandingsId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"points", Int64.Type}, {"position", Int64.Type}, {"positionText", Int64.Type}, {"wins", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

