table driver_standings
	lineageTag: af81b514-516b-4ada-af76-fd47e2e207b7

	measure Wincount = COUNT(driver_standings[wins])
		formatString: 0
		lineageTag: 6e292253-6078-445e-b8a0-da8703fd7343

	measure Racecount = COUNT(driver_standings[raceId])
		formatString: 0
		lineageTag: 88aeb60e-21ef-4c41-9114-3344dc8645e1

	column driverStandingsId
		dataType: int64
		formatString: 0
		lineageTag: 3d38fe99-e3fe-47b2-b0dd-9a23ba5d918e
		summarizeBy: count
		sourceColumn: driverStandingsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 65e64701-21f2-4f1f-b65c-c34917dcfa10
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 5eedb5f0-4292-4d91-bcb7-9594d8f56e3e
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 6d8c8ef3-f685-4a7d-bac3-ca72067e18bc
		summarizeBy: none
		sourceColumn: points

		annotation SummarizationSetBy = User

	column position
		dataType: int64
		formatString: 0
		lineageTag: 02c1d108-4346-4c48-8dd3-cc694e4d8bd6
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = User

	column positionText
		dataType: string
		lineageTag: 7b3abf23-fa61-4011-bdb4-0bcea16a6788
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: 1eefc72c-af2f-4b19-8d92-e498ff21e6e8
		summarizeBy: none
		sourceColumn: wins

		annotation SummarizationSetBy = User

	partition driver_standings = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MySQL\f1\driver_standings.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"driverStandingsId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"points", Int64.Type}, {"position", Int64.Type}, {"positionText", type text}, {"wins", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

