table driver_standings
	lineageTag: bc58b2ec-0d30-4d2a-a406-8ea1fdf0f55f

	column driverStandingsId
		dataType: int64
		formatString: 0
		lineageTag: 6da0091e-088a-4d89-bca6-8244d008020a
		summarizeBy: count
		sourceColumn: driverStandingsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: b2480bf9-090f-4343-abb9-391037886460
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: aa86cd5a-8a31-43f7-a6a2-b64ba19bb69d
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 45eab7a6-a7a5-4419-bc9b-1c79b3272162
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: 8c814d42-b0ae-455c-a299-d7da1ae22ccb
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: int64
		formatString: 0
		lineageTag: 14cbb7b8-0883-4eba-9317-48b016095297
		summarizeBy: sum
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: 039573e2-c722-4556-9b7b-77cd74532afc
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	partition driver_standings = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/driver_standings.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"driverStandingsId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"points", Int64.Type}, {"position", Int64.Type}, {"positionText", Int64.Type}, {"wins", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

