table lap_times
	lineageTag: ecd1567e-b13c-4b06-8176-69c265faa332

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 37efc853-3f51-4719-86b8-68af39eee528
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: ed7b4d8d-303e-42e4-a79b-c6c342f0ae25
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column lap
		dataType: int64
		formatString: 0
		lineageTag: fc749e64-b0b9-415e-a879-bf6a1af1c095
		summarizeBy: sum
		sourceColumn: lap

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: d90aa5d9-1700-4fd5-93ff-af5034e9aaf7
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column time
		dataType: string
		lineageTag: a1266b3d-bc23-4947-9c53-e83969586b2c
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column milliseconds
		dataType: int64
		formatString: 0
		lineageTag: c97ebc21-08e1-413f-bd70-a37715ac8ad9
		summarizeBy: sum
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	partition lap_times = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\lap_times.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"raceId", Int64.Type}, {"driverId", Int64.Type}, {"lap", Int64.Type}, {"position", Int64.Type}, {"time", type text}, {"milliseconds", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

