table lap_times
	lineageTag: 7798f8f7-2fb9-4b54-8af9-e49e6010ba5e

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: dfbef4a4-6aa2-4410-9a66-7b0ae5265063
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 7479da3f-c6ea-487a-85cd-2c06d1ff8efd
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column lap
		dataType: int64
		formatString: 0
		lineageTag: 2e51cfba-0798-4df1-8023-008bb7b92898
		summarizeBy: sum
		sourceColumn: lap

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: 5e3cb640-229d-4221-97bc-c5bb590a914f
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column time
		dataType: string
		lineageTag: 1ab36968-cad6-439f-b529-4af9e9826634
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column milliseconds
		dataType: int64
		formatString: 0
		lineageTag: 4ea50857-5400-42a4-8879-7d0e447923e8
		summarizeBy: sum
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	partition lap_times = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/lap_times.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"raceId", Int64.Type}, {"driverId", Int64.Type}, {"lap", Int64.Type}, {"position", Int64.Type}, {"time", type text}, {"milliseconds", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

