table 'pit_stops (2)'
	lineageTag: 1cfa5f96-813a-49ff-a9ea-48a8766e1d2e

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: e9189086-605f-4838-92f9-356f670d6282
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 35ae5958-18e0-4708-bc36-6cf6529355b9
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column stop
		dataType: int64
		formatString: 0
		lineageTag: 8b9bb0d0-6311-41e4-bfa0-7969499c4b60
		summarizeBy: sum
		sourceColumn: stop

		annotation SummarizationSetBy = Automatic

	column lap
		dataType: int64
		formatString: 0
		lineageTag: d00ae334-582c-4d8c-8e99-e062071660ed
		summarizeBy: sum
		sourceColumn: lap

		annotation SummarizationSetBy = Automatic

	column time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 953b21ad-6bf9-40ff-890e-7db5f1b12fc3
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column duration
		dataType: double
		lineageTag: 27d96d40-a24a-4629-967d-67bc13f311b3
		summarizeBy: sum
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column milliseconds
		dataType: int64
		formatString: 0
		lineageTag: 8b16b351-9cf8-4c48-8409-08836df00817
		summarizeBy: sum
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	partition 'pit_stops (2)' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\pit_stops.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"raceId", Int64.Type}, {"driverId", Int64.Type}, {"stop", Int64.Type}, {"lap", Int64.Type}, {"time", type time}, {"duration", type number}, {"milliseconds", Int64.Type}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"duration"})
				in
				    #"Removed Errors"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

