table pit_stops
	lineageTag: a91fef20-4173-442d-b900-105c4eb29574

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: b1936d9e-06fb-4584-92e1-c483543d0e0a
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 1da0d5a7-24d8-4568-a764-69a0a729d16d
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column stop
		dataType: int64
		formatString: 0
		lineageTag: 572fab83-9b01-4804-a0ad-e7f1ec004282
		summarizeBy: sum
		sourceColumn: stop

		annotation SummarizationSetBy = Automatic

	column lap
		dataType: int64
		formatString: 0
		lineageTag: 1f8121e9-12c7-4e08-a617-880553f328a1
		summarizeBy: sum
		sourceColumn: lap

		annotation SummarizationSetBy = Automatic

	column time
		dataType: dateTime
		formatString: Long Time
		lineageTag: d54ec6b4-49ed-454f-b652-e39df93b1fd4
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column duration
		dataType: double
		lineageTag: 19e552f0-46f2-4b14-9ae0-d4da79d9f40f
		summarizeBy: sum
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column milliseconds
		dataType: int64
		formatString: 0
		lineageTag: c2e7022c-eef4-4758-9b06-3c8a3eca81d7
		summarizeBy: sum
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	partition pit_stops = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/pit_stops.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"raceId", Int64.Type}, {"driverId", Int64.Type}, {"stop", Int64.Type}, {"lap", Int64.Type}, {"time", type time}, {"duration", type number}, {"milliseconds", Int64.Type}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"duration"})
				in
				    #"Removed Errors"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

