table qualifying
	lineageTag: 75deb5d8-ce89-4cfc-9e22-153809ee1abb

	column qualifyId
		dataType: int64
		formatString: 0
		lineageTag: d774f8d1-1c4f-4eb8-8758-80e67dcaa43c
		summarizeBy: count
		sourceColumn: qualifyId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 87df2388-bb50-496c-b61c-662c621e6b6e
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 6d3dd9aa-b69f-42fe-8c08-81e2a6fbc446
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 98cd746e-32d8-4e15-a300-1aa163a710a8
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column number
		dataType: int64
		formatString: 0
		lineageTag: 3f897abc-a05a-4e8c-9c50-38c9e3b48927
		summarizeBy: sum
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: 56afcd3a-d196-4d57-a9f4-f25a4f121298
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column q1
		dataType: string
		lineageTag: adc4b9e4-02e2-4dce-9d13-a7ca523fd32e
		summarizeBy: none
		sourceColumn: q1

		annotation SummarizationSetBy = Automatic

	column q2
		dataType: string
		lineageTag: 16b9af02-9587-4019-b84d-838e5d79bf6d
		summarizeBy: none
		sourceColumn: q2

		annotation SummarizationSetBy = Automatic

	column q3
		dataType: string
		lineageTag: 03bdd19b-e017-4abf-a061-251d8347729b
		summarizeBy: none
		sourceColumn: q3

		annotation SummarizationSetBy = Automatic

	partition qualifying = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\qualifying.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"qualifyId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"constructorId", Int64.Type}, {"number", Int64.Type}, {"position", Int64.Type}, {"q1", type text}, {"q2", type text}, {"q3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

