table qualifying
	lineageTag: 73d2df69-4a4a-4bca-85f4-7ebea67b9204

	column qualifyId
		dataType: int64
		formatString: 0
		lineageTag: db275d4f-184c-4cea-bb00-aea449f329ea
		summarizeBy: count
		sourceColumn: qualifyId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: aa035258-0e81-482c-9c91-345167e80e2c
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 1c882f18-45ce-409b-a99d-0692153d2d57
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: b38d6a6f-a5dc-4c66-aa9e-4a3c4d1b5047
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column number
		dataType: int64
		formatString: 0
		lineageTag: e5db2685-6db6-4242-8831-97e2474ae86d
		summarizeBy: sum
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: 9b0d7f00-6759-46eb-812f-0703a3e65c5f
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column q1
		dataType: string
		lineageTag: 0c8d6e7a-87d9-4d98-8894-0cfa5f956585
		summarizeBy: none
		sourceColumn: q1

		annotation SummarizationSetBy = Automatic

	column q2
		dataType: string
		lineageTag: 1c4fd05b-bf84-4fad-a13f-64b496f4ac34
		summarizeBy: none
		sourceColumn: q2

		annotation SummarizationSetBy = Automatic

	column q3
		dataType: string
		lineageTag: 4c1ace21-eee9-4f64-acbf-437749e8a1c7
		summarizeBy: none
		sourceColumn: q3

		annotation SummarizationSetBy = Automatic

	partition qualifying = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MySQL\f1\qualifying.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"qualifyId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"constructorId", Int64.Type}, {"number", Int64.Type}, {"position", Int64.Type}, {"q1", type text}, {"q2", type text}, {"q3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

