table qualifying
	lineageTag: d5073d9b-6d31-410d-9e85-aa39da36e891

	column qualifyId
		dataType: int64
		formatString: 0
		lineageTag: c845c8b3-178b-497b-8188-afcf2c2256fd
		summarizeBy: count
		sourceColumn: qualifyId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 5acf1120-0476-4596-be86-3ac93a2503e7
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: c7afe059-e74c-4eb0-bf22-f06e587918d5
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 2c6b4c66-aa5f-4b06-98eb-81669a8f4796
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column number
		dataType: int64
		formatString: 0
		lineageTag: 003f8d4b-49aa-4d85-84c1-f40345ff022a
		summarizeBy: sum
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: ef8ef4f7-fda8-4df8-874e-d8c7918f5971
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column q1
		dataType: string
		lineageTag: ce550e0a-f790-492c-accc-ba7c428aff2f
		summarizeBy: none
		sourceColumn: q1

		annotation SummarizationSetBy = Automatic

	column q2
		dataType: string
		lineageTag: 245ebd3b-b228-4b28-b5be-471b38b5ce08
		summarizeBy: none
		sourceColumn: q2

		annotation SummarizationSetBy = Automatic

	column q3
		dataType: string
		lineageTag: 91130361-56dd-4d54-8bdf-012faa73a52c
		summarizeBy: none
		sourceColumn: q3

		annotation SummarizationSetBy = Automatic

	partition qualifying = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/qualifying.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"qualifyId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"constructorId", Int64.Type}, {"number", Int64.Type}, {"position", Int64.Type}, {"q1", type text}, {"q2", type text}, {"q3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

