table races
	lineageTag: b89bce72-e6f1-468b-8476-26a5f81f8b0c

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 233bc24f-2b3a-42e5-aaf7-395feea7dd95
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: a89536e0-2762-4a2d-be4f-7afa6c037d5d
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column round
		dataType: int64
		formatString: 0
		lineageTag: 666dbfb0-1d97-49d1-970f-07232e84bd90
		summarizeBy: sum
		sourceColumn: round

		annotation SummarizationSetBy = Automatic

	column circuitId
		dataType: int64
		formatString: 0
		lineageTag: 2e53bfe9-ebc4-4ee1-af6e-33e63503a500
		summarizeBy: none
		sourceColumn: circuitId

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: ea4b3eb5-493c-49be-b26e-d58e08bbe291
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff9f4f15-80fa-49e1-8d89-b6c7fdca5870
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: d4033a6b-5512-4347-8279-9738d6859586
			defaultHierarchy: LocalDateTable_8376344a-4277-4e88-b04a-39f1c345678e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column time
		dataType: string
		lineageTag: cbe70b6b-b361-44f3-81a2-af0a2908d23c
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: c2814088-a480-4eee-9727-1b2e2795320a
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column fp1_date
		dataType: string
		lineageTag: 53ed352a-debf-4638-b11b-9122171737f1
		summarizeBy: none
		sourceColumn: fp1_date

		annotation SummarizationSetBy = Automatic

	column fp1_time
		dataType: string
		lineageTag: c573d004-4ac5-4dd6-8339-771f55fb4779
		summarizeBy: none
		sourceColumn: fp1_time

		annotation SummarizationSetBy = Automatic

	column fp2_date
		dataType: string
		lineageTag: d1c548fc-da4b-48e6-b7b0-ed5a965f6f03
		summarizeBy: none
		sourceColumn: fp2_date

		annotation SummarizationSetBy = Automatic

	column fp2_time
		dataType: string
		lineageTag: 0d7fab2e-c13d-4033-9849-8b5c900da56b
		summarizeBy: none
		sourceColumn: fp2_time

		annotation SummarizationSetBy = Automatic

	column fp3_date
		dataType: string
		lineageTag: 43f6dc5c-7f20-4e58-967e-2f67d371330b
		summarizeBy: none
		sourceColumn: fp3_date

		annotation SummarizationSetBy = Automatic

	column fp3_time
		dataType: string
		lineageTag: b9010806-b27e-48e5-bc3d-d657018af1d6
		summarizeBy: none
		sourceColumn: fp3_time

		annotation SummarizationSetBy = Automatic

	column quali_date
		dataType: string
		lineageTag: 033f4f69-be90-433d-9a63-a0e68c3316c8
		summarizeBy: none
		sourceColumn: quali_date

		annotation SummarizationSetBy = Automatic

	column quali_time
		dataType: string
		lineageTag: e85e9049-4274-47dd-951a-35f0f04de4e1
		summarizeBy: none
		sourceColumn: quali_time

		annotation SummarizationSetBy = Automatic

	column sprint_date
		dataType: string
		lineageTag: ebc09d6e-df0a-4a6e-b816-f2931df6d588
		summarizeBy: none
		sourceColumn: sprint_date

		annotation SummarizationSetBy = Automatic

	column sprint_time
		dataType: string
		lineageTag: 267f2a26-7b6a-41d7-917a-8bc5de7cba62
		summarizeBy: none
		sourceColumn: sprint_time

		annotation SummarizationSetBy = Automatic

	partition races = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\races.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"raceId", Int64.Type}, {"year", Int64.Type}, {"round", Int64.Type}, {"circuitId", Int64.Type}, {"name", type text}, {"date", type date}, {"time", type text}, {"url", type text}, {"fp1_date", type text}, {"fp1_time", type text}, {"fp2_date", type text}, {"fp2_time", type text}, {"fp3_date", type text}, {"fp3_time", type text}, {"quali_date", type text}, {"quali_time", type text}, {"sprint_date", type text}, {"sprint_time", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

