table races
	lineageTag: 1eab41af-960e-4b28-bc12-d08693f832a0

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 0606ac98-eef3-432e-9144-e6a816f65bd9
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: c6c4fa5d-9902-46ec-8145-d8b6f49b9a87
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column round
		dataType: int64
		formatString: 0
		lineageTag: e649464e-9508-4522-bb49-afa05bcfc4dc
		summarizeBy: sum
		sourceColumn: round

		annotation SummarizationSetBy = Automatic

	column circuitId
		dataType: int64
		formatString: 0
		lineageTag: 0bb11698-a100-4523-be84-67b85c8f3ff2
		summarizeBy: none
		sourceColumn: circuitId

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 46793a8f-1e83-42ff-b804-92ca7df2bc27
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e3186f86-e4b3-47ae-8382-939cf17c883f
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: c2dbbf7b-658e-490a-8801-d2a4ed9a3efc
			defaultHierarchy: LocalDateTable_abb21bec-2ec8-415a-a709-f48127e2e091.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column time
		dataType: string
		lineageTag: 412e7d9d-1c6a-475e-8fe5-00d319d946ec
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: d71118f6-e2b7-407a-9230-dad02c4a15d2
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column fp1_date
		dataType: string
		lineageTag: d21711e2-96df-4fac-87b3-2c19c0a96d95
		summarizeBy: none
		sourceColumn: fp1_date

		annotation SummarizationSetBy = Automatic

	column fp1_time
		dataType: string
		lineageTag: 22e1f71e-8340-4d40-8be5-bb41ebb593ab
		summarizeBy: none
		sourceColumn: fp1_time

		annotation SummarizationSetBy = Automatic

	column fp2_date
		dataType: string
		lineageTag: 9ba65c79-cb5d-477c-8497-02c053220c82
		summarizeBy: none
		sourceColumn: fp2_date

		annotation SummarizationSetBy = Automatic

	column fp2_time
		dataType: string
		lineageTag: ed3b75d8-8b17-46f7-95f7-df1746f0b6d8
		summarizeBy: none
		sourceColumn: fp2_time

		annotation SummarizationSetBy = Automatic

	column fp3_date
		dataType: string
		lineageTag: c1cf5f69-52ef-48fd-b906-cf5e4e586237
		summarizeBy: none
		sourceColumn: fp3_date

		annotation SummarizationSetBy = Automatic

	column fp3_time
		dataType: string
		lineageTag: ac885299-713e-45d0-bf79-e37bd4680b69
		summarizeBy: none
		sourceColumn: fp3_time

		annotation SummarizationSetBy = Automatic

	column quali_date
		dataType: string
		lineageTag: 9a289d6e-158b-48d7-afa9-0d924c2a5b52
		summarizeBy: none
		sourceColumn: quali_date

		annotation SummarizationSetBy = Automatic

	column quali_time
		dataType: string
		lineageTag: 6a1a30c5-d009-4103-b30e-e02a2633e1ae
		summarizeBy: none
		sourceColumn: quali_time

		annotation SummarizationSetBy = Automatic

	column sprint_date
		dataType: string
		lineageTag: 3718235b-81ac-439d-abe6-68e8fd57a19d
		summarizeBy: none
		sourceColumn: sprint_date

		annotation SummarizationSetBy = Automatic

	column sprint_time
		dataType: string
		lineageTag: 98e9c57a-8475-48f3-82a0-527189b07c1d
		summarizeBy: none
		sourceColumn: sprint_time

		annotation SummarizationSetBy = Automatic

	partition races = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/races.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"raceId", Int64.Type}, {"year", Int64.Type}, {"round", Int64.Type}, {"circuitId", Int64.Type}, {"name", type text}, {"date", type date}, {"time", type text}, {"url", type text}, {"fp1_date", type text}, {"fp1_time", type text}, {"fp2_date", type text}, {"fp2_time", type text}, {"fp3_date", type text}, {"fp3_time", type text}, {"quali_date", type text}, {"quali_time", type text}, {"sprint_date", type text}, {"sprint_time", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

