table 'results (2)'
	lineageTag: d2a84dfd-441e-470f-92e3-2723d13743aa

	column resultId
		dataType: int64
		formatString: 0
		lineageTag: 31e279b1-6a1d-454f-8923-505929d6a5f9
		summarizeBy: count
		sourceColumn: resultId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 838787fe-58f9-42e7-909e-22dc4ad1683c
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 238133c9-b803-4053-b263-c64eded36e43
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 91998e24-4f38-4c3b-894a-6e3b3639f83c
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column number
		dataType: int64
		formatString: 0
		lineageTag: a599587a-b1ab-4e0c-ad4a-e5fff579b7dc
		summarizeBy: sum
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column grid
		dataType: int64
		formatString: 0
		lineageTag: 61fda092-ba55-43cb-9e0b-05b02276af22
		summarizeBy: sum
		sourceColumn: grid

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: 898da259-8bfd-4865-bad3-f36c01a86719
		summarizeBy: sum
		sourceColumn: position

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: string
		lineageTag: cf55927f-5830-45c4-8918-96f067858db4
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column positionOrder
		dataType: int64
		formatString: 0
		lineageTag: 3cd607d0-c1c5-407d-8fd0-e7dcfaacc652
		summarizeBy: sum
		sourceColumn: positionOrder

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 6958befa-b8eb-47ab-9385-b00abcb569ce
		summarizeBy: none
		sourceColumn: points

		annotation SummarizationSetBy = User

	column laps
		dataType: int64
		formatString: 0
		lineageTag: 882b3ee3-aed9-46b0-acd8-4f8cc5acdc6f
		summarizeBy: sum
		sourceColumn: laps

		annotation SummarizationSetBy = Automatic

	column time
		dataType: string
		lineageTag: e0670502-2b09-4780-b94f-d416a139a098
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column milliseconds
		dataType: string
		lineageTag: 4f10ffae-6744-4b59-b4ba-3a0fd52fe051
		summarizeBy: none
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	column fastestLap
		dataType: string
		lineageTag: 0015a7c0-ad7f-4f5c-8b42-80ce86ad0d44
		summarizeBy: none
		sourceColumn: fastestLap

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: string
		lineageTag: 7656996a-e92e-4bb1-a9a1-bbc1a20356e3
		summarizeBy: none
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column fastestLapTime
		dataType: string
		lineageTag: d06e0341-39b5-49be-8656-a2be5a352cde
		summarizeBy: none
		sourceColumn: fastestLapTime

		annotation SummarizationSetBy = Automatic

	column fastestLapSpeed
		dataType: string
		lineageTag: b1f978f5-0ebc-4362-b3a4-cadc6fa47512
		summarizeBy: none
		sourceColumn: fastestLapSpeed

		annotation SummarizationSetBy = Automatic

	column statusId
		dataType: int64
		formatString: 0
		lineageTag: 1c5b61e4-fa95-43b0-8d17-a3e22f84e43c
		summarizeBy: none
		sourceColumn: statusId

		annotation SummarizationSetBy = Automatic

	partition 'results (2)' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\results.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"resultId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"constructorId", Int64.Type}, {"number", Int64.Type}, {"grid", Int64.Type}, {"position", type text}, {"positionText", type text}, {"positionOrder", Int64.Type}, {"points", Int64.Type}, {"laps", Int64.Type}, {"time", type text}, {"milliseconds", type text}, {"fastestLap", type text}, {"rank", type text}, {"fastestLapTime", type text}, {"fastestLapSpeed", type text}, {"statusId", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([position] <> "\N"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

