table results
	lineageTag: 11d6739a-a776-40b0-9b5b-e2cb903cba02

	column resultId
		dataType: int64
		formatString: 0
		lineageTag: 9e816102-a42c-42c6-aa0a-953f9d35b74e
		summarizeBy: count
		sourceColumn: resultId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 29b4f667-ba82-4d06-863a-e573dd202f6a
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: a6e84994-a759-4257-929f-181f393dccef
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: fdfc01aa-0a1f-446e-98af-8efaa0bbead3
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column number
		dataType: int64
		formatString: 0
		lineageTag: dfddefd2-7726-4d4f-84ab-8f4d93a83368
		summarizeBy: sum
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column grid
		dataType: int64
		formatString: 0
		lineageTag: 3b9603db-1e00-44c9-9903-bb9c72023a4a
		summarizeBy: sum
		sourceColumn: grid

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: a7ddcd9a-aa57-4b91-9450-7c4e9e5f496e
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = User

	column positionText
		dataType: string
		lineageTag: 08f75035-997a-4f01-9405-717878d44f39
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column positionOrder
		dataType: int64
		formatString: 0
		lineageTag: 505ce7ff-4a0a-442c-99d5-81a653d0504e
		summarizeBy: sum
		sourceColumn: positionOrder

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 38b82c1e-800a-4825-80bc-ff89f627a0d0
		summarizeBy: none
		sourceColumn: points

		annotation SummarizationSetBy = User

	column laps
		dataType: int64
		formatString: 0
		lineageTag: 1e0a908b-c305-4770-b5d2-25ee33226b21
		summarizeBy: sum
		sourceColumn: laps

		annotation SummarizationSetBy = Automatic

	column time
		dataType: string
		lineageTag: 4c05a8aa-5460-4386-b058-2904032f4836
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column milliseconds
		dataType: string
		lineageTag: 8091a0d3-6de1-4f4e-a44f-5c5d2ea00066
		summarizeBy: none
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	column fastestLap
		dataType: string
		lineageTag: 9fad21ba-5372-4ddc-bc6c-9b45fb442bae
		summarizeBy: none
		sourceColumn: fastestLap

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: string
		lineageTag: 543587a1-1037-4e15-96b2-f3f41d56e64e
		summarizeBy: none
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column fastestLapTime
		dataType: string
		lineageTag: 2f5eadca-9a08-4a4a-8e1b-640655835280
		summarizeBy: none
		sourceColumn: fastestLapTime

		annotation SummarizationSetBy = Automatic

	column fastestLapSpeed
		dataType: string
		lineageTag: 4f35fda8-8f40-4459-b3ac-1c2759ef7b7a
		summarizeBy: none
		sourceColumn: fastestLapSpeed

		annotation SummarizationSetBy = Automatic

	column statusId
		dataType: int64
		formatString: 0
		lineageTag: 1ba332a7-27db-4988-b101-9003e76bb749
		summarizeBy: none
		sourceColumn: statusId

		annotation SummarizationSetBy = Automatic

	partition results = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/results.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"resultId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"constructorId", Int64.Type}, {"number", Int64.Type}, {"grid", Int64.Type}, {"position", type text}, {"positionText", type text}, {"positionOrder", Int64.Type}, {"points", Int64.Type}, {"laps", Int64.Type}, {"time", type text}, {"milliseconds", type text}, {"fastestLap", type text}, {"rank", type text}, {"fastestLapTime", type text}, {"fastestLapSpeed", type text}, {"statusId", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([position] <> "\N")),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"position", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

