table seasons
	lineageTag: 9c6eb42e-b04b-4b9c-9279-de6ca4284aca

	column year
		dataType: int64
		formatString: 0
		lineageTag: a7536601-f130-4d82-af52-0e664c58e694
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: b426f11b-9fd3-4cba-a7b9-accabba3978e
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition seasons = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/seasons.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"year", Int64.Type}, {"url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

