table sprint_results
	lineageTag: 132ad80d-c2f5-48fe-aae4-44ac4bb194d4

	column resultId
		dataType: int64
		formatString: 0
		lineageTag: 70be3eac-dac5-4a6a-bce2-475666a11510
		summarizeBy: count
		sourceColumn: resultId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 73506186-be2a-4532-a023-a1c1056348c4
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: c26a44c8-9417-4348-ab67-a3ae30160de3
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: af467a96-dafc-4389-92bc-dc0f65c1f526
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column number
		dataType: int64
		formatString: 0
		lineageTag: 8d0b68e5-9d92-4798-8221-652f889249ea
		summarizeBy: sum
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column grid
		dataType: int64
		formatString: 0
		lineageTag: a3452447-f8c5-44b2-9e54-b84d4febe6e7
		summarizeBy: sum
		sourceColumn: grid

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		lineageTag: de15a777-f253-42fa-9652-f7cb98792229
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: string
		lineageTag: 0e8dfef1-236b-45a9-ad1d-1d5bdfd89840
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column positionOrder
		dataType: int64
		formatString: 0
		lineageTag: 5ab476b6-b330-42f5-b863-43251188f0b1
		summarizeBy: sum
		sourceColumn: positionOrder

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 90b7714b-d6d6-49b8-a58e-b5ffd3709949
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column laps
		dataType: int64
		formatString: 0
		lineageTag: 4db9927b-2685-442e-bc01-f5f0f5871813
		summarizeBy: sum
		sourceColumn: laps

		annotation SummarizationSetBy = Automatic

	column time
		dataType: string
		lineageTag: a738d253-2e5f-4bdd-8b61-697b53dcccb0
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column milliseconds
		dataType: string
		lineageTag: b6c8a493-4f9e-464d-ba26-2b1bf2ba1456
		summarizeBy: none
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	column fastestLap
		dataType: string
		lineageTag: 6d68755a-de58-4510-b668-39bbc9ca27d6
		summarizeBy: none
		sourceColumn: fastestLap

		annotation SummarizationSetBy = Automatic

	column fastestLapTime
		dataType: string
		lineageTag: 2cc0598e-ba96-46fe-838d-40176a0d3cbe
		summarizeBy: none
		sourceColumn: fastestLapTime

		annotation SummarizationSetBy = Automatic

	column statusId
		dataType: int64
		formatString: 0
		lineageTag: fbcfefbe-ea1c-4ef2-bc43-4146e76b6c63
		summarizeBy: none
		sourceColumn: statusId

		annotation SummarizationSetBy = Automatic

	partition sprint_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\sprint_results.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"resultId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"constructorId", Int64.Type}, {"number", Int64.Type}, {"grid", Int64.Type}, {"position", type text}, {"positionText", type text}, {"positionOrder", Int64.Type}, {"points", Int64.Type}, {"laps", Int64.Type}, {"time", type text}, {"milliseconds", type text}, {"fastestLap", type text}, {"fastestLapTime", type text}, {"statusId", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

