table sprint_results
	lineageTag: 637d722c-dd1a-4414-bdd4-f3db8b79b8db

	column resultId
		dataType: int64
		formatString: 0
		lineageTag: b3f601a0-5409-4c30-8006-970d0f0e7dd1
		summarizeBy: count
		sourceColumn: resultId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 3b60a05d-5bcf-462c-aa4e-157b2c5e25d6
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 65679025-c2b2-4cf5-992c-ce6f428135d1
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: df18f485-7f35-4bad-8dcd-69c87a86530b
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column number
		dataType: int64
		formatString: 0
		lineageTag: 65aa997d-0910-4f77-bb7d-7f3b93356584
		summarizeBy: sum
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column grid
		dataType: int64
		formatString: 0
		lineageTag: 1c3ee41c-1779-4db6-a477-fe143cfb04b5
		summarizeBy: sum
		sourceColumn: grid

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		lineageTag: 0efaebb6-4546-494a-8a62-51d66af3859e
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: string
		lineageTag: 31d251eb-621f-482e-a6aa-a6ffd639af6b
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column positionOrder
		dataType: int64
		formatString: 0
		lineageTag: ec20ea35-27fd-46aa-b4fa-128725d38af0
		summarizeBy: sum
		sourceColumn: positionOrder

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 7580bb95-2abc-4ab7-a3d8-86ad96ec8242
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column laps
		dataType: int64
		formatString: 0
		lineageTag: 6501e402-eccf-4c39-96f6-62365ef8fdd5
		summarizeBy: sum
		sourceColumn: laps

		annotation SummarizationSetBy = Automatic

	column time
		dataType: string
		lineageTag: 2cf3c7e1-9480-46ac-a4c2-4c768eae1726
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column milliseconds
		dataType: string
		lineageTag: 2f93785f-aef9-418a-b885-c9440cc09ebd
		summarizeBy: none
		sourceColumn: milliseconds

		annotation SummarizationSetBy = Automatic

	column fastestLap
		dataType: string
		lineageTag: e99e1342-dc5c-4885-bb66-f9884deb23df
		summarizeBy: none
		sourceColumn: fastestLap

		annotation SummarizationSetBy = Automatic

	column fastestLapTime
		dataType: string
		lineageTag: 33a96640-9d86-441c-b1c0-7712207eae59
		summarizeBy: none
		sourceColumn: fastestLapTime

		annotation SummarizationSetBy = Automatic

	column statusId
		dataType: int64
		formatString: 0
		lineageTag: 45211cbf-0e66-4deb-96c2-eaa234a27ddf
		summarizeBy: none
		sourceColumn: statusId

		annotation SummarizationSetBy = Automatic

	partition sprint_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/sprint_results.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"resultId", Int64.Type}, {"raceId", Int64.Type}, {"driverId", Int64.Type}, {"constructorId", Int64.Type}, {"number", Int64.Type}, {"grid", Int64.Type}, {"position", type text}, {"positionText", type text}, {"positionOrder", Int64.Type}, {"points", Int64.Type}, {"laps", Int64.Type}, {"time", type text}, {"milliseconds", type text}, {"fastestLap", type text}, {"fastestLapTime", type text}, {"statusId", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

