table status
	lineageTag: 40789869-60e5-4c6d-9d93-10f74da62acc

	column statusId
		dataType: int64
		formatString: 0
		lineageTag: 50862cb8-2cf8-44a7-8e72-5499f14f6c3e
		summarizeBy: none
		sourceColumn: statusId

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: a0bfd1fc-de83-4f6f-a6f7-12426e19e3cd
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition status = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://ltimindtree.sharepoint.com/sites/01LOrealAPACDelivery/Shared%20Documents/General/Trainings%20-%20BI%20Team/Trainee_Batch_3/Git%20RND/Dataset/status.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"statusId", Int64.Type}, {"status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

