table status
	lineageTag: 406d6862-d7b8-4769-b59d-0ce4685ea3dc

	column statusId
		dataType: int64
		formatString: 0
		lineageTag: f2c3c680-f772-48f4-974f-7d3dfd72a8ec
		summarizeBy: none
		sourceColumn: statusId

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: e95d8108-2206-40d3-8fff-074af4ae3148
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition status = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\10845381\OneDrive - LTIMindtree\f1\status.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"statusId", Int64.Type}, {"status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

